theme: minima
title: David's Website
description: This is my personal website created using Jekyll. 
baseurl: ""
url: "https://itangdav.github.io"
author:
  name: David Tang
  email: itangdav@gmail.com

minima:
  social_links:
    github: itangdav
    linkedin: david-tang-583a441a1

copyright: "David Tang"

header_pages:
  - about.md
  - projects.md
  - blog.md

plugins:
  - jekyll-redirect-from
  
whitelist:
  - jekyll-redirect-from

