theme: minima
title: David's Website
description: This is my personal website.
baseurl: ""
url: "https://itangdav.github.io"
github_username:  itangdav
email: itangdav@gmail.com
author: David Tang

skin: dark
  
header_pages:
  - about.md
  - projects.md
